/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-06 07:34:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.Console;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609826949404L));
    _jspx_dependants.put("jar:file:/D:/JavaStudy/Code/JavaSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JavaSSM/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.Console");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>员工列表</title>\r\n");

	pageContext.setAttribute("APP_PATH", request.getContextPath());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jQuery-2.2.0.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 显示页面 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- 标题 -->\r\n");
      out.write("\t\t<div clalss=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2>SSM_CRUD</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 按钮 -->\r\n");
      out.write("\t\t<div clalss=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-md-offset-8\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" id=\"emp_add\">新增</button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-danger\" id=\"delete_batch\">删除</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 表格 -->\r\n");
      out.write("\t\t<div clalss=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chkAll\">\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t<th>empName</th>\r\n");
      out.write("\t\t\t\t\t\t<th>gender</th>\r\n");
      out.write("\t\t\t\t\t\t<th>email</th>\r\n");
      out.write("\t\t\t\t\t\t<th>deptName</th>\r\n");
      out.write("\t\t\t\t\t\t<th>操作</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"tbody\">\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 分页 -->\r\n");
      out.write("\t\t<div clalss=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" id=\"pageInfo\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<nav aria-label=\"Page navigation\">\r\n");
      out.write("\t\t\t\t<ul class=\"pagination\" id=\"pagination\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 员工添加 -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"addEmp\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">新增员工</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\" id=\"formInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"empname\" class=\"col-sm-2 control-label\">EmpName</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"empName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"empName\"> <span id=\"emp_name_block\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"email\" placeholder=\"Email@qq.com\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"email_block\" class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">Gender</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" id=\"radM\" value=\"M\" checked=\"checked\"> 男\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" id=\"radF\" value=\"F\"> 女\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">DeptName</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"dId\" id=\"sltDept\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"saveInfo\">保存</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 员工修改 -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"editEmp\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">编辑员工</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\" id=\"formInfoEdit\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"empname\" class=\"col-sm-2 control-label\">EmpName</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"form-control-static\" id=\"edit_emp_name\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"edit_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"email\" placeholder=\"Email@qq.com\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"edit_email_block\" class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">Gender</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" id=\"radMEdit\" value=\"M\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t男\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" id=\"radFEdit\" value=\"F\"> 女\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">DeptName</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"dId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"saveInfoEdit\">修改</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar totalCount,currentPage;\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tgetEmps(1);\r\n");
      out.write("\t\t\t$(\"#emp_add\").click(function() {\r\n");
      out.write("\t\t\t\t//$(\"#formInfo\")[0].reset();\r\n");
      out.write("\t\t\t\treset_form(\"#formInfo\");\r\n");
      out.write("\t\t\t\tgetDepts(\"#formInfo select\");\r\n");
      out.write("\t\t\t\t$('#addEmp').modal({\r\n");
      out.write("\t\t\t\t\tbackdrop : 'static'\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//保存员工\r\n");
      out.write("\t\t\t$(\"#saveInfo\").click(function() {\r\n");
      out.write("\t\t\t\tvar info = $(\"#formInfo\").serialize();\r\n");
      out.write("\t\t\t\tif (!validateForm()) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar val = $(this).attr(\"validate\");\r\n");
      out.write("\t\t\t\tif (val == \"success\") {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emp\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdata : info,\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result.code == 200) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#addEmp\").modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\t//显示最后一页\r\n");
      out.write("\t\t\t\t\t\t\t\tgetEmps(totalCount);\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#saveInfoEdit\").click(function(){\r\n");
      out.write("\t\t\t\tvar email = $(\"#edit_email\").val();\r\n");
      out.write("\t\t\t\tvar empId= $(this).attr(\"empId\");\r\n");
      out.write("\t\t\t\tvar regEmail = /^([a-zA-Z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/\r\n");
      out.write("\t\t\t\tif (!regEmail.test(email)) {\r\n");
      out.write("\t\t\t\t\t$(\"#edit_email\").parent().addClass('has-error');\r\n");
      out.write("\t\t\t\t\t$(\"#edit_email_block\").html(\"邮箱格式不正确!\");\r\n");
      out.write("\t\t\t\t\t//alert(\"邮箱格式不正确!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#edit_email\").parent().addClass(\"has-success\").removeClass(\r\n");
      out.write("\t\t\t\t\t\t\t\"has-error\");\r\n");
      out.write("\t\t\t\t\t$(\"#edit_email_block\").html(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//保存更新的数据\r\n");
      out.write("\t\t\t\tvar putData= $(\"#formInfoEdit\").serialize()+\"&_method=PUT\";\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emp/\"+empId,\r\n");
      out.write("\t\t\t\t\ttype:\"put\",\r\n");
      out.write("\t\t\t\t\tdata:$(\"#formInfoEdit\").serialize(),\r\n");
      out.write("\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\tif (result.code == 200) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#editEmp\").modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t//返回当前页\r\n");
      out.write("\t\t\t\t\t\t\tgetEmps(currentPage);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//校验用户名是否可用\r\n");
      out.write("\t\t\t$(\"#empName\").change(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chkempname\",\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : \"empName=\" + $(this).val(),\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (result.code == 200) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//成功\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#empName\").parent().addClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"has-success\").removeClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"has-error\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#emp_name_block\").html(\"用户名可用\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#saveInfo\").attr(\"validate\", \"success\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//失败\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#empName\").parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.addClass(\"has-error\").removeClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"has-success\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#emp_name_block\").html(result.data.msg);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#saveInfo\").attr(\"validate\", \"error\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//编辑按钮点击\r\n");
      out.write("\t\t$(document).on(\"click\",\".edit_btn\",function(){\r\n");
      out.write("\t\t\tgetDepts(\"#formInfoEdit select\");\r\n");
      out.write("\t\t\tvar empId= $(this).attr(\"data-id\");\t\t\t\r\n");
      out.write("\t\t\tget_emp_info(empId);\r\n");
      out.write("\t\t\t$('#editEmp').modal({\r\n");
      out.write("\t\t\t\tbackdrop : 'static'\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//单个删除员工\r\n");
      out.write("\t\t$(document).on(\"click\",\".del_btn\",function(){\t\t\t\r\n");
      out.write("\t\t\tvar empId= $(this).attr(\"data-id\");\t\t\t\r\n");
      out.write("\t\t\tvar empName =$(this).parents(\"tr\").find(\"td:eq(2)\").text();\r\n");
      out.write("\t\t\tif(confirm(\"确认要删除员工[\"+empName+\"]吗？\")){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emp/\"+empId,\r\n");
      out.write("\t\t\t\t\ttype:\"DELETE\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\tif (result.code == 200) {\r\n");
      out.write("\t\t\t\t\t\t\t//返回当前页\r\n");
      out.write("\t\t\t\t\t\t\tgetEmps(currentPage);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction get_emp_info(empId){\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emp/\"+empId,\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tif(result.code==200){\r\n");
      out.write("\t\t\t\t\t\tvar empInfo= result.data.emp; \r\n");
      out.write("\t\t\t\t\t\t$(\"#edit_emp_name\").text(empInfo.empName);\r\n");
      out.write("\t\t\t\t\t\t$(\"#edit_email\").val(empInfo.email);\r\n");
      out.write("\t\t\t\t\t\t$(\"#formInfoEdit select\").val(empInfo.dId);\r\n");
      out.write("\t\t\t\t\t\t$(\"#formInfoEdit input[name=gender]\").val([empInfo.gender]);\r\n");
      out.write("\t\t\t\t\t\t$(\"#saveInfoEdit\").attr(\"empId\",empInfo.empId);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction reset_form(ele) {\r\n");
      out.write("\t\t\t$(ele)[0].reset();\r\n");
      out.write("\t\t\t$(ele).find(\"*\").removeClass(\"has-error has-success\");\r\n");
      out.write("\t\t\t$(ele).find(\".help-block\").html(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction validateForm() {\r\n");
      out.write("\t\t\tvar emp_name = $(\"#empName\").val();\r\n");
      out.write("\t\t\tvar regName = /(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\\u9FFF]{2,5}$)/;\r\n");
      out.write("\t\t\tif (!regName.test(emp_name)) {\r\n");
      out.write("\t\t\t\t//alert(\"用户名可以是2-5位中文或者6-16位英文和数字的组合!\");\r\n");
      out.write("\t\t\t\t$(\"#empName\").parent().addClass(\"has-error\");\r\n");
      out.write("\t\t\t\t$(\"#emp_name_block\").html(\"用户名可用是2-5位中文或者6-16位英文和数字的组合!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#empName\").parent().addClass(\"has-success\").removeClass(\r\n");
      out.write("\t\t\t\t\t\t\"has-error\");\r\n");
      out.write("\t\t\t\t$(\"#emp_name_block\").html(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar email = $(\"#email\").val();\r\n");
      out.write("\t\t\tvar regEmail = /^([a-zA-Z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/\r\n");
      out.write("\t\t\tif (!regEmail.test(email)) {\r\n");
      out.write("\t\t\t\t$(\"#email\").parent().addClass('has-error');\r\n");
      out.write("\t\t\t\t$(\"#email_block\").html(\"邮箱格式不正确!\");\r\n");
      out.write("\t\t\t\t//alert(\"邮箱格式不正确!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#email\").parent().addClass(\"has-success\").removeClass(\r\n");
      out.write("\t\t\t\t\t\t\"has-error\");\r\n");
      out.write("\t\t\t\t$(\"#email_block\").html(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getDepts(ele) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/depts\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tinitDept(result.data.dept,ele);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction initDept(deptList,ele) {\r\n");
      out.write("\t\t\t$(ele).empty();\r\n");
      out.write("\t\t\t$.each(deptList, function(index, item) {\r\n");
      out.write("\t\t\t\t$(\"<option></option>\").attr(\"value\", item.deptId).append(\r\n");
      out.write("\t\t\t\t\t\titem.deptName).appendTo(ele);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getEmps(pageIndex) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emps\",\r\n");
      out.write("\t\t\t\tdata : \"pageIndex=\" + pageIndex,\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t//1.解析并显示员工数据\r\n");
      out.write("\t\t\t\t\tset_emps_table(result);\r\n");
      out.write("\t\t\t\t\t//2.解析分页信息\r\n");
      out.write("\t\t\t\t\tset_page_info(result.data.pageInfo);\r\n");
      out.write("\t\t\t\t\tset_page_nav(result.data.pageInfo);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction set_emps_table(result) {\r\n");
      out.write("\t\t\t$(\"#tbody\").empty();\r\n");
      out.write("\t\t\tvar emps = result.data.pageInfo.list;\r\n");
      out.write("\t\t\t$\r\n");
      out.write("\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\temps,\r\n");
      out.write("\t\t\t\t\t\t\tfunction(index, item) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar chkTd=$('<td><input type=\"checkbox\" class=\"chk_item\" value=\"'+item.empId+'\" ></td>'); \r\n");
      out.write("\t\t\t\t\t\t\t\tvar empIdTd = $(\"<td></td>\").append(item.empId);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar empNameTd = $(\"<td></td>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titem.empName);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar gender = item.gender == \"M\" ? \"男\" : \"女\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar genderTd = $(\"<td></td>\").append(gender);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar emailTd = $(\"<td></td>\").append(item.email);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar empDepartTd = $(\"<td></td>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titem.dept.deptName);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar _editBtn = '<button class=\"btn btn-primary btn-sm edit_btn\" data-id=\"'+item.empId+'\" >修改</button>';\r\n");
      out.write("\t\t\t\t\t\t\t\tvar _deleteBtn = '<button class=\"btn btn-danger btn-sm del_btn\" data-id=\"'+item.empId+'\">删除</button>';\r\n");
      out.write("\t\t\t\t\t\t\t\tvar handleTd = $(\"<td></td>\").append(_editBtn)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.append(_deleteBtn);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<tr></tr>\").append(chkTd)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.append(empIdTd)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.append(empNameTd).append(genderTd)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.append(emailTd).append(empDepartTd)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.append(handleTd).appendTo(\"#tbody\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction set_page_info(pageInfo) {\r\n");
      out.write("\t\t\t$(\"#pageInfo\").html(\r\n");
      out.write("\t\t\t\t\t\"当前\" + pageInfo.pageNum + \"页,总\" + pageInfo.pages + \"页,总\"\r\n");
      out.write("\t\t\t\t\t\t\t+ pageInfo.total + \"条记录\");\r\n");
      out.write("\t\t\ttotalCount = pageInfo.total;\r\n");
      out.write("\t\t\tcurrentPage= pageInfo.pageNum;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction set_page_nav(pageInfo) {\r\n");
      out.write("\t\t\tvar _page_nav = \"\";\r\n");
      out.write("\t\t\t_page_nav += '<li onclick=\"getEmps(1)\"><a href=\"#\" >首页</a></li>';\r\n");
      out.write("\t\t\tif (pageInfo.hasPreviousPage) {\r\n");
      out.write("\t\t\t\t_page_nav += '<li><a onclick=\"getEmps('\r\n");
      out.write("\t\t\t\t\t\t+ (pageInfo.pageNum - 1)\r\n");
      out.write("\t\t\t\t\t\t+ ')\" href=\"#\" aria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span></a></li>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.each(pageInfo.navigatepageNums, function(index, item) {\r\n");
      out.write("\t\t\t\tif (pageInfo.pageNum == item) {\r\n");
      out.write("\t\t\t\t\t_page_nav += '<li class=\"active\"><a onclick=\"getEmps('\r\n");
      out.write("\t\t\t\t\t\t\t+ item + ')\" href=\"#\">' + item + '</a></li>';\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t_page_nav += '<li><a onclick=\"getEmps(' + item\r\n");
      out.write("\t\t\t\t\t\t\t+ ')\" href=\"#\">' + item + '</a></li>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tif (pageInfo.hasNextPage) {\r\n");
      out.write("\t\t\t\t_page_nav += '<li><a onclick=\"getEmps('\r\n");
      out.write("\t\t\t\t\t\t+ (pageInfo.pageNum + 1)\r\n");
      out.write("\t\t\t\t\t\t+ ')\" href=\"#\" aria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span></a></li>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t_page_nav += '<li><a onclick=\"getEmps(' + pageInfo.pages\r\n");
      out.write("\t\t\t\t\t+ ')\" href=\"#\">末页</a></li>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#pagination\").html(_page_nav);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//全选\t\t\r\n");
      out.write("\t\t$(\"#chkAll\").click(function(){\r\n");
      out.write("\t\t\tvar chk=\t$(this).prop(\"checked\");\r\n");
      out.write("\t\t\t$(\".chk_item\").prop(\"checked\",chk);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\",\".chk_item\",function(){\r\n");
      out.write("\t\t   var chkLength=$(\".chk_item:checked\").length;\r\n");
      out.write("\t\t   var itemLength=$(\".chk_item\").length;\r\n");
      out.write("\t\t   if(chkLength==itemLength){\r\n");
      out.write("\t\t\t   $(\"#chkAll\").prop(\"checked\",true);   \r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   $(\"#chkAll\").prop(\"checked\",false);\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#delete_batch\").click(function(){\r\n");
      out.write("\t\t\tvar empNames=\"\";\r\n");
      out.write("\t\t\tvar del_id=\"\";\r\n");
      out.write("\t\t\t$.each($(\".chk_item:checked\"),function(){\r\n");
      out.write("\t\t\t\tempNames+=$(this).parents(\"tr\").find(\"td:eq(2)\").text()+\",\";\t\t\r\n");
      out.write("\t\t\t\tdel_id+= $(this).val()+\"-\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tif(empNames==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请选择要删除的员工！\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tempNames=empNames.substring(0,empNames.length-1);\r\n");
      out.write("\t\t\tdel_id= del_id.substring(0,del_id.length-1);\r\n");
      out.write("\t\t\tconsole.log(del_id);\r\n");
      out.write("\t\t\tif(confirm(\"确认删除员工【\"+empNames+\"】吗\")){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emp/\"+del_id,\r\n");
      out.write("\t\t\t\t\ttype:\"DELETE\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\tif (result.code == 200) {\r\n");
      out.write("\t\t\t\t\t\t\t//返回当前页\r\n");
      out.write("\t\t\t\t\t\t\tgetEmps(currentPage);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
